name: EpicSellWands
version: maven-version-number
description: EpicSellWands
author: Craftaro
main: com.craftaro.epicsellwands.EpicSellWands
softdepend: [Vault, ModdedCore]
api-version: 1.13

commands:
  esw:
    description: Give other players sell wands.
    usage: /sellwands
    aliases: [EpicSellWands]